version: "3"
services:
  bot:
    container_name: art-bot-helper
    command: python main.py
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /conf/art-bot-config:/app/configs
    env_file:
      - stack.env
    restart: unless-stopped